name: 'CI'

env:
  VERSION: 4.0.0
  ASM_VERSION: 4.0.0

on:
  push:
    branches:
      - master
      - delta
    paths:
      - src/*

  pull_request:
    branches:
      - master
    paths:
      - src/*

  workflow_dispatch:

jobs:
  build-codecs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: ${{ matrix.os }} codecs
    steps:
    - uses: actions/checkout@v2
    - name: get-cmake
      uses: lukka/get-cmake@v3.21.1
      

  test:
    name: Test on ${{ matrix.os }}
    needs: [ build-codecs ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: 'test on ${{ matrix.os }}'
      run: dotnet test src/Parquet.sln -c release

  pack:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build src/Parquet.sln -c release /p:Version=$VERSION /p:FileVersion=$VERSION /p:AssemblyVersion=$ASM_VERSION


  deploy-nuget:
    needs: [ pack ]
    environment: nuget
    runs-on: ubuntu-latest